### PR TITLE
First Half of Issue #1 (Parsing of {})

### PR DESCRIPTION
**Pull request by kwando1313**
We implemented the first half of issue #1, which was to allow {} to be parsed to group objects together.

We tested the following implementations of this syntax: 

dispEv, foo, c {'profiles', 1+shift+$bar$}, {lr}:

dispEv, foo, c ,{'profiles', 1+shift+$bar$}, {lr}:

dispEv, foo}, c {'profiles', 1+shift+$bar$}, {lr}:

dispEv, {foo, c {'profiles', 1+shift+$bar$}, {lr}:

Note: The parser was smart enough to realize that we don't need escape characters if we (ever) write a string like this:  dispEv, fo{o, c {'profiles', 1+shift+$bar$}, {lr}:

### CODE REVIEW

**Comment by Enthalpy-AC** [comment]
Thanks, but I'm afraid this commit has some issues. Going down the list:
- I need first_directory/frame_data.txt restored.
- For aesthetic reasons, I'd prefer if you followed the 79 character rule for each line.
- Lines 69-70: Why do you need these patterns in the first place? Any unescaped brace is assumed to have syntactic meaning. There's no need to check whether the character right before or after is a comma, space, or such.
- Line 69: The first regex pattern doesn't make sense. Except for brackets, special characters don't exist inside an excluded class, so why are there three / characters?
- Line 69: Replace the re.compile calls with re.match calls. The only reason to use re.compile is if the same pattern is being used several times in the same program. Using re.match directly allows for clearer code.
- Line 69: Combine the two regex search strings using |.
- Line 70: Incorrect whitespace. Notice how this line is indented oddly, relative to everything else? Did you use mixed whitespace, or just not add enough spaces?
- Line 71: There should be spaces around colons in dictonary key-values pairs.
- Line 71: Why does adding a space before a curly brace create a newline? The newline trick is used to tell Catalysis the points to break the modified text string into a list of arguments, wherever unescaped comma-space appears. Whether or not a curly brace is preceded by a space has nothing to do with this.
- Documentation needs to be updated, in general. For example, line 73 is no longer accurate, nor are 73-5.
- At this stage, different arguments should always be separated by a comma, even if they're enclosed in curly braces. If these tests allowed "dispEv, foo, c {'profiles', 1+shift+$bar$}, {lr}:" as if there was a comma right after the c, this suggests a bug.

**Comment by Enthalpy-AC** [comment]
Edited out "commit history" concerns from list of issues to fix.

**Comment by kwando1313** [comment]
I believe that all the changes have been made, as required...

**Comment by Enthalpy-AC** [comment]
Almost there. Can you change the docstring on func, lines 63-5, to reflect that it also handles { and } characters? That's the last issue.

**Pull request merged**
